### PR TITLE
Bug/allowed cancel a past meeting

### LINKED ISSUE #20: Allowed cancel a past meeting
the user that cannot cancel a past meeting

### PR DESCRIPTION
**Pull request by KsquarianMike**
Closes #20

### CODE REVIEW

File: test/Users.ts [hunk 1]
```diff
@@ -0,0 +1,256 @@
...
+
+  /*
+  * Test the /GET route
+  */
+  describe("GET", () => {
+    it("it should get the user", (done) => {
+      chai.request(apiPath)
+          .get(userId)
+          .set("Authorization", token)
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 2]
```diff
@@ -0,0 +1,256 @@
...
+            res.body.should.have.property("email");
+            done();
+          });
+    });
+
+    it("it should not get the user if it does not exist", (done) => {
+      chai.request(apiPath)
+          .get("100")
+          .set("Authorization", token)
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 3]
```diff
@@ -0,0 +1,256 @@
...
+            res.body.should.be.an("string").and.equal("Not Found");
+            done();
+          });
+    });
+
+    it("it should not get the user if token is not correct", (done) => {
+      chai.request(apiPath)
+          .get(userId)
+          .set("Authorization", "")
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 4]
```diff
@@ -0,0 +1,256 @@
...
+              name: "JsonWebTokenError"
+            });
+            done();
+          });
+    });
+
+    it("it should not get the user if token is not provided", (done) => {
+      chai.request(apiPath)
+          .get(userId)
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 5]
```diff
@@ -0,0 +1,256 @@
...
+          .type("form")
+          .send({
+            email: "testEdited@test.com",
+            name: "testEdited",
+            password: "test1234",
+            picture: "newURL",
+            role: "admin"
+          })
+          .set("Authorization", token)
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 6]
```diff
@@ -0,0 +1,256 @@
...
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 7]
```diff
@@ -0,0 +1,256 @@
...
+          .type("form")
+          .send({
+            email: "testEdited@test.com",
+            name: "testEdited",
+            password: "test1234",
+            picture: "newURL",
+            role: "admin"
+          })
+          .set("Authorization", "")
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 8]
```diff
@@ -0,0 +1,256 @@
...
+          .put(userId)
+          .type("form")
+          .send({
+            email: "testEdited@test.com",
+            name: "testEdited",
+            password: "test1234",
+            picture: "newURL",
+            role: "admin"
+          })
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 9]
```diff
@@ -0,0 +1,256 @@
...
+
+  /*
+  * Test the /DELETE route
+  */
+  describe("DELETE", () => {
+    it("it should delete the user", (done) => {
+      chai.request(apiPath)
+          .delete(userId)
+          .set("Authorization", token)
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 10]
```diff
@@ -0,0 +1,256 @@
...
+            res.body.should.be.an("object");
+            done();
+          });
+    });
+
+    it("it should not delete the user if it does not exist", (done) => {
+      chai.request(apiPath)
+          .delete(userId)
+          .set("Authorization", token)
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 11]
```diff
@@ -0,0 +1,256 @@
...
+            done();
+          });
+    });
+
+    it("it should not delete the user if token is not correct", (done) => {
+      chai.request(apiPath)
+          .delete(userId)
+          .set("Authorization", "")
+          .end((err, res) => {
+            res.should.have.status(401);
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 12]
```diff
@@ -0,0 +1,256 @@
...
+              name: "JsonWebTokenError"
+            });
+            done();
+          });
+    });
+
+    it("it should not delete the user if token is not provided", (done) => {
+      chai.request(apiPath)
+          .delete(userId)
+          .end((err, res) => {
```
Comment (mishelashala) [inline test/Users.ts]: add error handling:

```js
if (err) {
  throw err
}
```

File: test/Users.ts [hunk 13]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+          res.should.have.status(200);
+          res.body.should.be.an("object");
+          res.body.should.have.property("id");
+          res.body.should.have.property("auth_provider_id");
+          res.body.should.have.property("picture");
+          res.body.should.have.property("name");
+          res.body.should.have.property("email");
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 14]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+      chai
+        .request(apiPath)
+        .get("100")
+        .set("Authorization", token)
+        .end((err, res) => {
+          res.should.have.status(404);
+          res.body.should.be.an("string").and.equal("Not Found");
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 15]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+        .set("Authorization", "")
+        .end((err, res) => {
+          res.should.have.status(401);
+          res.body.should.be.an("object").and.deep.equal({
+            message: "jwt must be provided",
+            name: "JsonWebTokenError"
           });
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 16]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+    it("it should not get the user if token is not provided", done => {
+      chai
+        .request(apiPath)
+        .get(userId)
+        .end((err, res) => {
+          res.should.have.status(401);
+          res.body.should.be.an("string").and.equal("No Token Present");
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 17]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
-            role: "admin"
-          })
-          .set("Authorization", token)
-          .end((err, res) => {
-            res.should.have.status(404);
-            // res.body.should.be.an("string").and.equal("Not Found");
-            res.body.should.be.an("object").and.deep.equal({});
-            done();
-          });
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 18]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
-          .set("Authorization", "")
-          .end((err, res) => {
-            res.should.have.status(401);
-            res.body.should.be.an("object").and.deep.equal({
-              message: "jwt must be provided",
-              name: "JsonWebTokenError"
-            });
-            done();
-          });
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 19]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+        .set("Authorization", "")
+        .end((err, res) => {
+          res.should.have.status(401);
+          res.body.should.be.an("object").and.deep.equal({
+            message: "jwt must be provided",
+            name: "JsonWebTokenError"
           });
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 20]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+          password: "test1234",
+          picture: "newURL",
+          role: "admin"
+        })
+        .end((err, res) => {
+          res.should.have.status(401);
+          res.body.should.be.an("string").and.equal("No Token Present");
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 21]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+      chai
+        .request(apiPath)
+        .delete(userId)
+        .set("Authorization", token)
+        .end((err, res) => {
+          res.should.have.status(204);
+          res.body.should.be.an("object");
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 22]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+      chai
+        .request(apiPath)
+        .delete(userId)
+        .set("Authorization", token)
+        .end((err, res) => {
+          res.should.have.status(404);
+          res.body.should.be.an("object").and.deep.equal({});
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 23]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+        .set("Authorization", "")
+        .end((err, res) => {
+          res.should.have.status(401);
+          res.body.should.be.an("object").and.deep.equal({
+            message: "jwt must be provided",
+            name: "JsonWebTokenError"
           });
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top

File: test/Users.ts [hunk 24]
```diff
@@ -31,226 +31,280 @@ describe("User", () => {
...
+    it("it should not delete the user if token is not provided", done => {
+      chai
+        .request(apiPath)
+        .delete(userId)
+        .end((err, res) => {
+          res.should.have.status(401);
+          res.body.should.be.an("string").and.equal("No Token Present");
+          done();
+
+          if (err) {
```
Comment (mishelashala) [inline test/Users.ts]: error should be at top
