### PR TITLE
Bug/verify bookings date

### LINKED ISSUE #15: fix: missing booking date verification
+ The booking only can have office hours (Monday-Friday, 9AM-6PM).
+ Not allow reservations in past days.

### PR DESCRIPTION
**Pull request by KsquarianMike**
closes #15

### CODE REVIEW

File: app/controllers/v1/Booking.ts [hunk 1]
```diff
@@ -268,6 +272,16 @@ export class BookingController extends Controller {
         res,
         "Bad Request: No attendes as Array in request"
       );
+    } else if (getActualDate() > data.body.start) {
```
Comment (mishelashala) [inline app/controllers/v1/Booking.ts]: If you are using `early-return` there's no need to use `else-if`

```js
if (somePredicate) {
  return someCode()
}

if (otherPredicate) {
  return otherThing()
}
```

File: app/services/GoogleCalendarService.ts [hunk 2]
```diff
@@ -40,7 +40,7 @@ class GoogleCalendarService {
       .then(result => {
         return result;
       })
-      .catch(err => Controller.serverError(err));
+      .catch(err => Controller.serverError(err, err));
```
Comment (mishelashala) [inline app/services/GoogleCalendarService.ts]: why do you need to pass error twice?
