### PR TITLE
Bug/missing email validation

### LINKED ISSUE #14: fix: missing email validation
Validate the emails in the following endpoints:

- POST /api/v1/booking
- PUT /api/v1/booking

### PR DESCRIPTION
**Pull request by KsquarianMike**
closes #14

### CODE REVIEW

File: app/config/config.ts [hunk 1]
```diff
@@ -94,6 +94,14 @@ export const config: any = {
         "gmail.com"
       ]
     }
+  },
+
+  serviceAccount: {
+    key: process.env.KEY_SERVICE_ACCOUNT || "The key must be in file .env",
```
Comment (mishelashala) [inline app/config/config.ts]: duplicated changes, see #16

File: app/controllers/v1/Booking.ts [hunk 2]
```diff
@@ -1,7 +1,12 @@
 import * as _ from "lodash";
 import { Op } from "sequelize";
 import { Controller } from "./../../libraries/Controller";
-import { isEmpty } from "./../../libraries/util";
+import {
+  isEmpty,
+  getActualDate,
+  isAvailableDate,
+  areValidsEmails
+} from "./../../libraries/util";
```
Comment (mishelashala) [inline app/controllers/v1/Booking.ts]: duplicated changes, see #16

File: app/libraries/util.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import * as moment from "moment-timezone";
+import * as EmailValidator from "email-validator";
```
Comment (mishelashala) [inline app/libraries/util.ts]: duplicated changes, see #16

File: app/services/GoogleCalendarService.ts [hunk 4]
```diff
@@ -1,6 +1,6 @@
 import * as CalendarAPI from "node-google-calendar";
 import { Controller } from "./../libraries/Controller";
-import { config } from "./../config/configService";
+import { config } from "./../config/config";
```
Comment (mishelashala) [inline app/services/GoogleCalendarService.ts]: duplicated changes, see #16
